/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 725f71ce32c4275d7e4dd45f8ff1c08d)
interface __BaseEnv_Env {
	METRICS: AnalyticsEngineDataset;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
